[package]
name = "oxydized-money-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
rust_decimal_macros = { version = "1.34.2", features = ["reexportable"] }

[build-dependencies]
iso_currency = { version = "0.4.4", features = ["iterator"] }
